### ISSUE TITLE
Latest commit 0af9acb causes issues with Flatpak

### ISSUE THREAD

**Issue by RGarciaLago** [raspberrypi-ui/raspberrypi-ui-mods#7]
From forum thread: https://forums.raspberrypi.com/viewtopic.php?t=379077

I'm having this issue as well on my end. Based on the comments in that thread; adding the dirs that are missing for flatpak fixes the issue.

**Comment by RGarciaLago** [comment]
Unfortunately I don't know how to fix it locally for me so I'm hoping raising this issue is of some help. I appreciate the hard work y'all do, Raspberry Pi OS is amazing!

**Comment by spl237** [comment]
Unfortunately, an environment variable change which it turns out was required to make flatpak work was causing a crash under certain circumstances with labwc, and our priority has to be to make labwc work properly.

Flatpak makes changes to the XDG_DATA_DIRS environment varIable. When the desktop starts, these changes are now overwritten.

The mechanism by which this happens is not satisfactory, and it is not immediately obvious how to make this work with both systems.

For anyone using flatpak, if you modify the value of XDG_DATA_DIRS set in /etc/xdg/labwc/environment by appending ":XDG_DATA_DIRS" to the end, flatpak will then work again, but bear in mind that this may cause instability with labwc, particularly when reloading settings.

I will look to see if there is a way of making both systems work, but I cannot currently think of a way that isn't a rather kludgy hack.

**Comment by RGarciaLago** [comment]
@spl237 thanks for the detailed response! Would it be helpful if I crosspost this issue on the Flatpak’s GitHub and reference this issue?

**Comment by spl237** [comment]
> @spl237 thanks for the detailed response! Would it be helpful if I crosspost this issue on the Flatpak’s GitHub and reference this issue?

Probably not - I suspect they are likely to say it is our problem!

For the time being, I've pushed a temporary fix - I'm not entirely happy with it, but it should mean that both labwc and flatpak can play nicely until I can come up with something I am happy with!

It'll be going through the build system for a few hours but will hopefully be available as an apt update some time over the weekend.

**Comment by RGarciaLago** [comment]
Cheers, friend! Thanks for taking a look at this and putting together a temp fix so quickly. Y’all are knocking it out of the park!

**Comment by RGarciaLago** [comment]
Confirmed fixed with [Commmit 997e4a6](https://github.com/raspberrypi-ui/raspberrypi-ui-mods/commit/997e4a69a62372b85bce3f57a50af1329682a26b). Marking as resolved.

**Comment by spl237** [comment]
Thanks for testing!
